/**
 * Emits apps/web CSS custom properties from tokens.ts so the web surface can never
 * drift from the app. Run via `pnpm tokens:css` after any token change.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { darkColors, lightColors } from '../src/theme/semantic';
import {
  fontFamilyWeb,
  motion,
  palette,
  radius,
  space,
  typography,
} from '../src/theme/tokens';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '../../../apps/web/app/globals.css');

const kebab = (s: string) => s.replace(/([a-z])([A-Z0-9])/g, '$1-$2').toLowerCase();

const block = (entries: [string, string | number][], indent = '  ') =>
  entries.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

const paletteVars = Object.entries(palette).map(
  ([k, v]) => [`--color-${kebab(k)}`, v] as [string, string],
);
const spaceVars = Object.entries(space).map(([k, v]) => [`--s-${k}`, `${v}px`] as [string, string]);
const radiusVars = Object.entries(radius).map(
  ([k, v]) => [`--r-${k}`, `${v}px`] as [string, string],
);
const typeVars = Object.entries(typography).flatMap(([name, t]) => [
  [`--type-${kebab(name)}-size`, `${t.fontSize}px`],
  [`--type-${kebab(name)}-weight`, t.fontWeight],
  [`--type-${kebab(name)}-tracking`, `${t.letterSpacing}px`],
  [`--type-${kebab(name)}-leading`, `${t.lineHeight}px`],
]) as [string, string][];
const motionVars: [string, string][] = [
  ['--motion-fast', `${motion.fast}ms`],
  ['--motion-default', `${motion.default}ms`],
  ['--motion-slow', `${motion.slow}ms`],
  ['--easing', `cubic-bezier(${motion.easing.join(',')})`],
];
const fontVars: [string, string][] = [
  ['--font-sans', fontFamilyWeb.sans],
  ['--font-mono', fontFamilyWeb.mono],
];
const roleVars = (roles: Record<string, string>) =>
  Object.entries(roles).map(([k, v]) => [`--${kebab(k)}`, v] as [string, string]);

const css = `/* GENERATED by packages/shared/scripts/tokens-to-css.ts — do not edit by hand. */

:root {
${block([...paletteVars, ...spaceVars, ...radiusVars, ...typeVars, ...motionVars, ...fontVars])}

  /* semantic roles — light */
${block(roleVars(lightColors))}
}

/* semantic roles — dark, explicit choice wins in both directions */
:root[data-theme='dark'] {
${block(roleVars(darkColors))}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${block(roleVars(darkColors), '    ')}
  }
}

body {
  margin: 0;
  background: var(--surface);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: var(--type-body-size);
  line-height: var(--type-body-leading);
}
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, css, 'utf8');
console.log(`wrote ${target}`);
